feat: lint file extension

diff --git a/lefthook.yaml b/lefthook.yaml
--- a/lefthook.yaml
+++ b/lefthook.yaml
@@ -14,6 +14,16 @@ pre-commit:
       glob: '*.md'
       run: npx -y markdownlint-cli2 {staged_files}
 
+    lint-file-extension-yaml:
+      files: git diff --name-only --staged
+      glob: '*.yml'
+      run: echo "Error! ".yml" extension found, please use ".yaml" instead." && exit 1
+
+    lint-file-extension-storybook:
+      files: git diff --name-only --staged
+      glob: '*.story.{tsx,mdx}'
+      run: echo "Error! "*.story.{tsx,mdx}" extension found, please use "*.stories.{tsx,mdx}" instead." && exit 1
+
 commit-msg:
   parallel: true
 
